# [START ECHO TERRAFORM INPUTS]
steps:
    - id: 'Echo Current FIle'
      name: 'alpine'
      entrypoint: 'sh'
      args:
      - '-c'
      - |
          echo "******************************"
          echo "Beginning Terraform Building"
          echo "******************************"
    # [END ECHO TERRAFORM INPUTS]

    # [START TF Tools]

    - id: 'IAC Process'
      name: 'alpine'
      entrypoint: 'sh'
      args:
      - '-c'
      - |

        echo "****************************** root"
        echo "Beginning epoxy Building"
        echo "Workspace: ${_WORK_SPACE}"
        export WORK_SPACE=${_WORK_SPACE}
        echo "Environment: ${_ENVIRONMENT}"
        export ENVIRONMENT=${_ENVIRONMENT}
        echo "Commit COMMIT_HASH: ${_COMMIT_HASH}"
        export COMMIT_HASH=${_COMMIT_HASH}
        echo "Commit BRANCH: ${_BRANCH}"
        export BRANCH=${_BRANCH}
        echo "PROJECT_ID: ${_PROJECT_ID}"
        export PROJECT_ID=${_PROJECT_ID}
        echo "PROJECT_NAME: ${_PROJECT_NAME}"
        export PROJECT_NAME=${_PROJECT_NAME}
        echo "REGION: ${_REGION}"
        export REGION=${_REGION}
        echo "VERSION: ${_VERSION}"
        export VERSION=${_VERSION}
        echo "ARTIFACTORY_USERNAME: ${_ARTIFACTORY_USERNAME}"
        echo "ARTIFACTORY_PASSWORD: ${_ARTIFACTORY_PASSWORD} WARRING: please don't print this value once you know how to access the password "
        echo "WorkSpace: ${_WORK_SPACE}"
        echo "******************************"
        echo "******************************"

        echo "******************************"
        echo "Install deployment tools"
        chmod 777 ./tools/install.sh
        cd ${_WORK_SPACE}
        source ./tools/install.sh
        yarn
        yarn build
        ls -l dist
        gcloud config set project $_PROJECT_NAME
        gsutil cp -r $_UPLOAD_DIR $_BUCKET_NAME/$_APP_NAME/

timeout: 3600s
